window:
  padding:
    x: 20
    y: 15

shell:
  program: /bin/zsh

font:
  normal:
    family: JetBrains Mono
    style: Bold

  bold:
    family: JetBrains Mono
    style: ExtraBold

  italic:
    family: JetBrains Mono
    style: Bold Italic

  bold_italic:
    family: JetBrains Mono
    style: ExtraBold Italic

  size: 6

colors:
  primary:
    background: "#151515"
    foreground: "#D0D0D0"

  normal:
    black: "#151515"
    red: "#AC4142"
    green: "#90A959"
    yellow: "#F4BF75"
    blue: "#6A9FB5"
    magenta: "#AA759F"
    cyan: "#75B5AA"
    white: "#D0D0D0"

  bright:
    black: "#2D2D2D"
    red: "#AC4142"
    green: "#90A959"
    yellow: "#F4BF75"
    blue: "#6A9FB5"
    magenta: "#AA759F"
    cyan: "#75B5AA"
    white: "#D0D0D0"
