[colors.normal]
black = "#111111"
blue = "#b0b0b0"
cyan = "#828282"
green = "#999999"
magenta = "#a4a4a4"
red = "#8e8e8e"
white = "#bbbbbb"
yellow = "#777777"

[colors.primary]
background = "#111111"
foreground = "#bbbbbb"

[font]
size = 6

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[shell]
program = "/bin/zsh"

[window.padding]
x = 20
y = 15
